language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: true
node_js:
  - '8.9.3'
before_install:
  - npm install -g npm@5.6.0
  - npm install -g greenkeeper-lockfile@1
jobs:
  include:
    - stage: test
      script:
        - npm run build
        - npm run lint
        - npm run test
      before_script: greenkeeper-lockfile-update
      after_script: greenkeeper-lockfile-upload
    - stage: deploy
      if: branch = master
      script: npm run deploy
