language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: true
node_js:
  - 'node'
  - 'lts/*'
install: yarn install
before_install:
  - yarn global add npm@5
  - yarn global add greenkeeper-lockfile@1
jobs:
  include:
    - stage: test
      script:
        - yarn build
        - yarn build:prod
        - yarn lint
        - yarn test
      before_script: greenkeeper-lockfile-update
      after_script: greenkeeper-lockfile-upload
    - stage: deploy
      if: branch = master
      script:
        - yarn deploy
